FROM python:3.12-slim

WORKDIR /backend

COPY . .

RUN apt-get update -y && pip install poetry && poetry install

ENV PYTHONPATH=.

EXPOSE 8000

# CMD ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
