name: Run Tests
on:
  push:
    branches:
      - "feature/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout all the submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: upgrade python
        run: sudo add-apt-repository ppa:deadsnakes/ppa -y && sudo apt update -y && sudo apt install python3.12 -y
      - name: install deps
        run: pip install poetry && poetry install
      - name: run tests
        run: poetry run make tests
